name: Build Go Scanner

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build binaries
      run: |
        go mod init reality-scanner
        
        # Скачиваем основные зависимости
        go get github.com/refraction-networking/utls
        go get golang.org/x/net/http2/hpack
        go get golang.org/x/sync/errgroup
        go get golang.org/x/sync/singleflight
        go get golang.org/x/net/publicsuffix
        go mod tidy
        
        # 1. Сборка для Linux (amd64)
        echo "Building for Linux..."
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o reality-scanner-linux main.go

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: reality-scanner-binaries
        path: |
          reality-scanner-linux
